Repository Weasyl/weasyl, pull requests merged in 2018-06, with the labels that each got.

#301 Prevent TypeError when visiting a 2FA signin route with no session.
  weasyl/controllers/user.py
Labels: bug

#369 Add missing rel="nofollow" for external scheme-relative URLs
  libweasyl/libweasyl/defang.py
  libweasyl/libweasyl/test/test_text.py
Labels: bug

#373 Improve loading times for submission notifications
  weasyl/controllers/api.py
  weasyl/controllers/messages.py
  weasyl/message.py
Labels: performance

#376 Fix session token not changing on login and potential CSRF timing vulnerability
  weasyl/controllers/decorators.py
  weasyl/controllers/two_factor_auth.py
  weasyl/controllers/user.py
  weasyl/login.py
  weasyl/middleware.py
  weasyl/oauth2.py
  weasyl/profile.py
  weasyl/sessions.py
  weasyl/test/conftest.py
  weasyl/test/db_utils.py
  weasyl/test/login/test_authenticate_bcrypt.py
  weasyl/test/login/test_signin.py
  weasyl/test/resetpassword/test_force.py
  weasyl/test/web/test_login.py
Labels: security

#377 Remove some unnecessary `get_current_request()`s
  weasyl/api.py
  weasyl/controllers/decorators.py
  weasyl/controllers/two_factor_auth.py
  weasyl/define.py
Labels: cleanup

#378 Stateless guest sessions
  .gitignore
  libweasyl/libweasyl/models/users.py
  pyramid.md
  weasyl/controllers/decorators.py
  weasyl/define.py
  weasyl/login.py
  weasyl/middleware.py
  weasyl/sessions.py
  weasyl/test/conftest.py
  weasyl/test/web/test_blacklist.py
  weasyl/test/web/test_characters.py
  weasyl/test/web/test_journals.py
  weasyl/test/web/test_login.py
  weasyl/test/web/test_site_updates.py
  weasyl/test/web/wsgi.py
Labels: performance

#379 Fix notifications about characters with no tags
  weasyl/message.py
Labels: bug

#381 Avoid redundant friend, follow, and follower queries on profile page
  templates/user/profile.html
  weasyl/controllers/api.py
  weasyl/controllers/profile.py
  weasyl/followuser.py
  weasyl/frienduser.py
  weasyl/profile.py
Labels: performance

#385 Check login session early for editing journals
  weasyl/controllers/content.py
  weasyl/test/web/test_journals.py
Labels: bug, security
