Repository Weasyl/weasyl, pull requests merged in 2018-05, with the labels that each got.

#353 Remove unused define.webpage()/common_page_start() options
  static/pager/pager.js
  weasyl/controllers/detail.py
  weasyl/controllers/general.py
  weasyl/controllers/profile.py
  weasyl/controllers/settings.py
Labels: cleanup

#354 Only load PDF.js for PDF submissions
  weasyl/controllers/detail.py
Labels: enhancement

#328 Track IP/UA for sessions. Track IP for user creation.
  libweasyl/libweasyl/alembic/versions/5491fc6b3d51_track_ip_and_ua_in_session.py
  libweasyl/libweasyl/models/tables.py
  templates/admincontrol/finduser.html
  templates/admincontrol/manageuser.html
  weasyl/controllers/admin.py
  weasyl/controllers/user.py
  weasyl/login.py
  weasyl/moderation.py
  weasyl/profile.py
Labels: enhancement, moderation

#363 Remove some unused parts
  weasyl/image.py
  weasyl/login.py
  weasyl/test/login/test_verify.py
  weasyl/thumbnail.py
Labels: cleanup

#313 Leverage HTTP/2 Server Push to deliver render-blocking resources
  Vagrantfile
  etc/nginx.conf
  weasyl/middleware.py
  weasyl/wsgi.py
Labels: performance
