Repository Weasyl/weasyl, pull requests merged in 2019-09, with the labels that each got.

#575 Add lazy load exemptions for above-the-fold images
  templates/common/thumbnail_grid_item.html
  templates/etc/index.html
  templates/etc/popular.html
  templates/etc/search.html
  templates/message/submissions_thumbnails.html
  templates/user/characters.html
  templates/user/collections.html
  templates/user/favorites.html
  templates/user/profile.html
  templates/user/submissions.html
Labels: enhancement

#596 Use a NO ACTION action for ondelete/onupdate for columns
  libweasyl/libweasyl/alembic/versions/fb60c8528489_spam_filtering_correct_onupdate_ondelete.py
  libweasyl/libweasyl/models/tables.py
Labels: bug

#597 Remove unused/broken premium leftovers
  etc/SETTINGS.txt
  libweasyl/libweasyl/alembic/versions/0dd45a91821c_remove_unused_premium_leftovers.py
  libweasyl/libweasyl/models/tables.py
  templates/email/verify_premium.html
  weasyl/controllers/routes.py
  weasyl/controllers/user.py
  weasyl/errorcode.py
  weasyl/premiumpurchase.py
  weasyl/submission.py
  weasyl/test/useralias/test_select.py
  weasyl/useralias.py
Labels: cleanup
