Repository Weasyl/weasyl, pull requests merged in 2020-06, with the labels that each got.

#822 Increase the file size limit for visual submissions from 10 MiB to 50 MiB
  weasyl/character.py
  weasyl/submission.py
  weasyl/templates/submit/character.html
  weasyl/templates/submit/visual.html
Labels: enhancement

#829 Fix password reset requests with uppercase in local part
  weasyl/resetpassword.py
  weasyl/test/resetpassword/test_request.py
Labels: bug

#830 Set coverfile default value to empty string
  weasyl/controllers/content.py
Labels: bug, cleanup
