Repository Weasyl/weasyl, pull requests merged in 2020-02, with the labels that each got.

#689 Redirect halloweasyl2014 page to its tag
  weasyl/controllers/events.py
  weasyl/templates/events/halloweasyl.html
Labels: bug

#699 Cleanup
  libweasyl/libweasyl/conftest.py
  libweasyl/libweasyl/media.py
  libweasyl/libweasyl/models/content.py
  libweasyl/libweasyl/models/meta.py
  libweasyl/libweasyl/models/site.py
  libweasyl/libweasyl/models/users.py
  libweasyl/libweasyl/test/common.py
  weasyl/avatar.py
  weasyl/compat.py
  weasyl/controllers/decorators.py
  weasyl/controllers/general.py
  weasyl/controllers/profile.py
  weasyl/controllers/settings.py
  weasyl/controllers/user.py
  weasyl/define.py
  weasyl/errorcode.py
  weasyl/templates/detail/character.html
  weasyl/templates/detail/submission.html
  weasyl/templates/error/error.html
  weasyl/templates/etc/site_update.html
  weasyl/templates/etc/site_update_list.html
  weasyl/templates/manage/avatar_nostyle.html
  weasyl/templates/modcontrol/report.html
Labels: cleanup

#716 Update link format for some of the most common sources of old-style submission links
  weasyl/controllers/detail.py
  weasyl/controllers/profile.py
  weasyl/submission.py
  weasyl/templates/detail/submission.html
  weasyl/templates/user/profile.html
  weasyl/test/conftest.py
  weasyl/test/test_submission.py
Labels: cleanup, enhancement

#721 Remove unused and fragile __json__ implementations
  libweasyl/docs/source/common.rst
  libweasyl/libweasyl/common.py
  libweasyl/libweasyl/models/content.py
  libweasyl/libweasyl/models/media.py
  libweasyl/libweasyl/models/meta.py
  libweasyl/libweasyl/models/users.py
  weasyl/controllers/api.py
Labels: cleanup

#718 Remove unused templates
  weasyl/templates/commission/dib.html
  weasyl/templates/detail/commission.html
  weasyl/templates/etc/updates.html
  weasyl/templates/submit/commission.html
  weasyl/templates/user/commissions.html
Labels: cleanup

#724 Reference constraint file for weasyl to fix libweasyl builds.
  libweasyl/Makefile
Labels: bug

#728 Don’t treat user as optional when listing favorites
  weasyl/controllers/profile.py
  weasyl/favorite.py
Labels: cleanup

#726 Remove unused populators from libweasyl.media; adapt tests to weasyl.media
  libweasyl/libweasyl/media.py
  libweasyl/libweasyl/test/common.py
  libweasyl/libweasyl/test/test_media.py
  weasyl/test/test_media.py
  weasyl/test/utils.py
Labels: cleanup

#727 Use `<a download>` for download button
  weasyl/templates/detail/character.html
  weasyl/templates/detail/submission.html
Labels: bug

#730 Use Node 13
  .travis.yml
  Vagrantfile
Labels: cleanup, dependencies

#732 Remove with /modcontrol/edituserconfig route with missing implementation
  weasyl/controllers/moderation.py
  weasyl/controllers/routes.py
Labels: cleanup

#731 Remove custom Twisted Request implementation
  weasyl/polecat.py
Labels: cleanup

#734 Remove unused Submission.create()
  libweasyl/libweasyl/constants.py
  libweasyl/libweasyl/exceptions.py
  libweasyl/libweasyl/models/content.py
  libweasyl/libweasyl/models/helpers.py
  libweasyl/libweasyl/models/media.py
  libweasyl/libweasyl/models/test/test_content.py
  libweasyl/libweasyl/models/users.py
  weasyl/orm.py
  weasyl/searchtag.py
  weasyl/test/db_utils.py
  weasyl/test/web/common.py
  weasyl/test/web/test_submissions.py
Labels: cleanup

#736 Clear outdated optimized image representations when reuploading a visual submission
  libweasyl/libweasyl/models/media.py
  weasyl/submission.py
Labels: bug

#741 Remove define.convert_inputdate in favor of using define.convert_unix…
  weasyl/define.py
  weasyl/profile.py
  weasyl/templates/admincontrol/manageuser.html
Labels: cleanup

#739 Split login CharSettings column to distinct Boolean columns.
  etc/SETTINGS.txt
  libweasyl/libweasyl/alembic/versions/c1f8375b5805_split_login_charsettings_to_columns.py
  libweasyl/libweasyl/models/tables.py
  weasyl/commishinfo.py
  weasyl/controllers/routes.py
  weasyl/controllers/user.py
  weasyl/define.py
  weasyl/login.py
  weasyl/middleware.py
  weasyl/moderation.py
  weasyl/profile.py
  weasyl/resetpassword.py
  weasyl/shout.py
  weasyl/templates/force/resetbirthday.html
  weasyl/test/db_utils.py
  weasyl/test/login/test_authenticate_bcrypt.py
Labels: bug, cleanup

#742 Cleanup
  weasyl/define.py
  weasyl/templates/control/edit_profile.html
Labels: cleanup, enhancement

#745 Fix /admincontrol/finduser for removed login.settings
  weasyl/moderation.py
  weasyl/templates/admincontrol/finduser.html
Labels: bug

#743 Allow users to change their own usernames
  libweasyl/libweasyl/alembic/versions/4b6fd0d48a2b_add_username_history.py
  libweasyl/libweasyl/models/tables.py
  weasyl/controllers/moderation.py
  weasyl/controllers/profile.py
  weasyl/controllers/routes.py
  weasyl/controllers/settings.py
  weasyl/define.py
  weasyl/embed.py
  weasyl/errorcode.py
  weasyl/login.py
  weasyl/moderation.py
  weasyl/profile.py
  weasyl/templates/control/control.html
  weasyl/templates/control/edit_profile.html
  weasyl/templates/control/username.html
  weasyl/templates/help/faq.html
  weasyl/test/login/test_create.py
  weasyl/test/web/test_login.py
  weasyl/useralias.py
Labels: enhancement

#749 Restore memcached stats headers
  weasyl/cache.py
  weasyl/middleware.py
  weasyl/weasyl.tac
  weasyl/wsgi.py
Labels: bug, enhancement

#750 Make profile folder previews show most recent, obey blacklists
  weasyl/controllers/profile.py
  weasyl/folder.py
Labels: bug, enhancement

#754 Obey custom thumbnail display preference for folder previews
  weasyl/folder.py
  weasyl/templates/user/profile.html
Labels: bug, enhancement

#756 Fill in submission.favorites for submissions that haven’t been favorited since its introduction
  Dockerfile
  libweasyl/libweasyl/alembic/versions/5a6d74c75fa6_fill_in_favorite_count_for_submissions.py
  libweasyl/libweasyl/models/tables.py
  libweasyl/libweasyl/test/common.py
  weasyl/favorite.py
  weasyl/profile.py
  weasyl/submission.py
Labels: cleanup, enhancement

#761 Remove more unused parts of libweasyl.models.users
  libweasyl/libweasyl/models/users.py
Labels: cleanup
