Repository Weasyl/weasyl, pull requests merged in 2021-07, with the labels that each got.

#1059 Add SVG favicon
  assets/img/favicon-mask.svg
  assets/img/favicon.svg
  weasyl/templates/common/page_start.html
Labels: enhancement, ui

#1058 Fix test deprecation warnings
  libweasyl/libweasyl/text.py
  weasyl/config.py
  weasyl/test/login/test_authenticate_bcrypt.py
  weasyl/test/test_submission.py
Labels: cleanup

#1062 Add external-web network to web container
  docker-compose.yml
Labels: bug

#1056 Embed cleanup
  weasyl/embed.py
  weasyl/templates/help/faq.html
  weasyl/templates/submit/multimedia.html
Labels: cleanup

#1057 Remove unused or redundant media properties
  libweasyl/libweasyl/models/media.py
  weasyl/submission.py
Labels: cleanup, performance

#1064 Fix rating restriction on folder navigation between own submissions in SFW mode
  weasyl/submission.py
  weasyl/test/db_utils.py
  weasyl/test/web/test_submissions.py
Labels: bug

#1063 Perform JSON serialization at the pylibmc client level; remove gzip
  etc/requirements.txt
  libweasyl/libweasyl/cache.py
  libweasyl/libweasyl/conftest.py
  libweasyl/setup.py
  weasyl/test/conftest.py
  weasyl/weasyl.tac
Labels: cleanup, performance

#1065 Remove leftover of moderate rating in search
  weasyl/search.py
Labels: cleanup

#1066 Remove styled file inputs
  assets/js/scripts.js
  assets/scss/site.scss
  weasyl/templates/manage/avatar.html
  weasyl/templates/manage/banner.html
  weasyl/templates/submit/character.html
  weasyl/templates/submit/literary.html
  weasyl/templates/submit/multimedia.html
  weasyl/templates/submit/reupload_cover.html
  weasyl/templates/submit/reupload_submission.html
  weasyl/templates/submit/visual.html
Labels: bug, ui

#1067 Assorted comment improvements
  assets/js/scripts.js
  weasyl/comment.py
  weasyl/controllers/content.py
  weasyl/templates/common/comment_thread.html
Labels: bug, enhancement, ui

#1068 Remove fancy tag input
  assets/img/icon-delete.png
  assets/js/scripts.js
  assets/scss/site.scss
  weasyl/templates/common/detail_tag_form.html
  weasyl/templates/submit/multimedia.html
  weasyl/templates/submit/visual.html
Labels: bug, ui

#1071 CSS cleanup
  assets/scss/site.scss
Labels: cleanup

#1073 Fix exchange rate fetching for Python 3
  weasyl/commishinfo.py
Labels: bug

#1072 Upgrade Sentry client from raven to sentry-sdk
  config/site.config.txt.example
  etc/requirements.txt
  weasyl/cache.py
  weasyl/commishinfo.py
  weasyl/define.py
  weasyl/image.py
  weasyl/middleware.py
  weasyl/test/conftest.py
  weasyl/wsgi.py
Labels: cleanup, enhancement, ops

#1075 Index sorted inbox/outbox views
  libweasyl/libweasyl/alembic/versions/ed80016034fd_index_sorted_inbox_view.py
  libweasyl/libweasyl/models/tables.py
Labels: bug, performance

#1076 Remove `weasyl.cron` and perform its former tasks lazily
  ci/site.config.txt
  config/site.config.txt.example
  libweasyl/libweasyl/alembic/versions/89ee13bfd34f_remove_cron_runs.py
  libweasyl/libweasyl/alembic/versions/bcc54170c4e1_add_timestamp_to_views.py
  libweasyl/libweasyl/models/tables.py
  setup.cfg
  weasyl/cron.py
  weasyl/define.py
  weasyl/index.py
  weasyl/login.py
  weasyl/polecat.py
  weasyl/submission.py
  weasyl/weasyl.tac
Labels: cleanup

#1079 Replace Twisted with Gunicorn
  .dockerignore
  .gitignore
  Dockerfile
  ci/site.config.txt
  config/site.config.txt.example
  docker-compose.yml
  etc/requirements.txt
  gunicorn.conf.py
  weasyl/middleware.py
  weasyl/polecat.py
  weasyl/test/conftest.py
  weasyl/weasyl.tac
  weasyl/wsgi.py
Labels: cleanup

#1085 Fix autolinking applied incorrectly inside in HTML links
  libweasyl/libweasyl/test/test_text.py
  libweasyl/libweasyl/text.py
Labels: bug

#1084 Login experience improvements
  assets/js/scripts.js
  assets/scss/site.scss
  weasyl/controllers/routes.py
  weasyl/controllers/user.py
  weasyl/define.py
  weasyl/templates/common/page_start.html
  weasyl/templates/etc/login_box.html
  weasyl/templates/etc/signin.html
  weasyl/test/web/test_login.py
  weasyl/test/web/test_site_updates.py
Labels: bug, cleanup, enhancement, security, ui

#1088 Native social site name completion
  assets/js/scripts.js
  assets/js/typeahead.bundle.min.js
  assets/scss/site.scss
  weasyl/controllers/settings.py
  weasyl/templates/common/page_end.html
  weasyl/templates/control/edit_profile.html
Labels: cleanup, enhancement, ui

#1089 Rely on `Origin` header for CSRF prevention
  .github/workflows/tests.yml
  Dockerfile
  assets/js/scripts.js
  ci/site.config.txt
  config/site.config.txt.example
  etc/requirements.txt
  libweasyl/libweasyl/models/tables.py
  libweasyl/libweasyl/models/users.py
  weasyl/controllers/decorators.py
  weasyl/controllers/settings.py
  weasyl/controllers/two_factor_auth.py
  weasyl/controllers/user.py
  weasyl/define.py
  weasyl/login.py
  weasyl/middleware.py
  weasyl/profile.py
  weasyl/sessions.py
  weasyl/templates/common/page_start.html
  weasyl/test/conftest.py
  weasyl/test/login/test_signin.py
  weasyl/test/web/test_api.py
  weasyl/test/web/test_blacklist.py
  weasyl/test/web/test_characters.py
  weasyl/test/web/test_journals.py
  weasyl/test/web/test_login.py
  weasyl/test/web/test_notes.py
  weasyl/test/web/test_site_updates.py
  weasyl/test/web/test_submissions.py
  weasyl/wsgi.py
Labels: cleanup, enhancement, performance, security

#1091 Address SQLAlchemy 1.4 warnings
  docker-compose.yml
  libweasyl/libweasyl/models/helpers.py
  libweasyl/libweasyl/models/tables.py
  weasyl/frienduser.py
  weasyl/searchtag.py
Labels: cleanup

#1092 Improve performance of submission, gallery pages
  libweasyl/libweasyl/alembic/versions/41a6dbe0266d_index_submission_userid_submitid.py
  libweasyl/libweasyl/models/tables.py
  weasyl/controllers/profile.py
  weasyl/pagination.py
  weasyl/submission.py
  weasyl/templates/common/page_navigation.html
Labels: performance

#1095 Remove outdated index condition
  libweasyl/libweasyl/alembic/versions/bcb0d75b6f8b_remove_outdated_index_condition.py
  libweasyl/libweasyl/models/tables.py
  weasyl/submission.py
Labels: cleanup

#1096 Add submission tag history index
  libweasyl/libweasyl/alembic/versions/af3b8d60b7ba_add_submission_tag_history_index.py
  libweasyl/libweasyl/models/tables.py
Labels: bug, performance

#229 Submission settings columns
  etc/SETTINGS.txt
  libweasyl/libweasyl/alembic/versions/30ddd5fc6d26_submission_settings_columns.py
  libweasyl/libweasyl/models/content.py
  libweasyl/libweasyl/models/tables.py
  libweasyl/libweasyl/test/common.py
  weasyl/collection.py
  weasyl/comment.py
  weasyl/controllers/content.py
  weasyl/controllers/detail.py
  weasyl/favorite.py
  weasyl/folder.py
  weasyl/macro.py
  weasyl/message.py
  weasyl/moderation.py
  weasyl/profile.py
  weasyl/report.py
  weasyl/search.py
  weasyl/submission.py
  weasyl/templates/detail/submission.html
  weasyl/templates/edit/submission.html
  weasyl/templates/modcontrol/contentbyuser.html
  weasyl/templates/modcontrol/reports.html
  weasyl/test/db_utils.py
  weasyl/test/test_collection.py
  weasyl/test/test_submission.py
  weasyl/welcome.py
Labels: cleanup

#1098 Fix rendered Markdown trailing `<` caused by new `lxml.html.tostring` trailing newline
  libweasyl/libweasyl/text.py
Labels: bug

#1097 Prepare to split journal and character hidden/friends-only into columns
  libweasyl/libweasyl/alembic/versions/1fbcfecd195e_create_journal_and_character_hidden_.py
  libweasyl/libweasyl/models/content.py
  libweasyl/libweasyl/models/tables.py
  weasyl/character.py
  weasyl/controllers/content.py
  weasyl/controllers/moderation.py
  weasyl/controllers/routes.py
  weasyl/journal.py
  weasyl/macro.py
  weasyl/moderation.py
Labels: cleanup

#1099 Transition to exclusive use of hidden/friends-only columns for journals and characters
  libweasyl/libweasyl/alembic/versions/e2bedd00b085_fill_journal_and_character_hidden_.py
  libweasyl/libweasyl/models/content.py
  libweasyl/libweasyl/models/tables.py
  weasyl/character.py
  weasyl/favorite.py
  weasyl/journal.py
  weasyl/macro.py
  weasyl/moderation.py
  weasyl/profile.py
  weasyl/report.py
  weasyl/submission.py
  weasyl/templates/detail/character.html
  weasyl/templates/detail/journal.html
  weasyl/templates/detail/submission.html
  weasyl/templates/edit/character.html
  weasyl/templates/edit/journal.html
  weasyl/templates/modcontrol/contentbyuser.html
  weasyl/test/db_utils.py
  weasyl/test/test_character.py
  weasyl/test/test_journal.py
  weasyl/test/web/test_journals.py
  weasyl/welcome.py
Labels: cleanup

#1101 Streamline signup (part 1)
  weasyl/controllers/settings.py
  weasyl/controllers/user.py
  weasyl/errorcode.py
  weasyl/login.py
  weasyl/profile.py
  weasyl/resetpassword.py
  weasyl/templates/control/edit_emailpassword.html
  weasyl/templates/etc/resetpassword.html
  weasyl/templates/etc/signup.html
  weasyl/test/login/test_create.py
  weasyl/test/login/test_get_account_verification_token.py
  weasyl/test/resetpassword/test_reset.py
  weasyl/test/test_profile.py
Labels: enhancement, ui
