Repository Weasyl/weasyl, pull requests merged in 2021-03, with the labels that each got.

#936 Combine functions duplicated between weasyl.image and libweasyl.images
  libweasyl/libweasyl/images.py
  weasyl/character.py
  weasyl/image.py
  weasyl/media.py
  weasyl/submission.py
Labels: cleanup

#938 Restrict crossposting to source domains supported by Waxpost
  weasyl/errorcode.py
  weasyl/submission.py
  weasyl/test/web/common.py
  weasyl/test/web/test_submissions.py
Labels: bug, security

#941 Remove unused Markdown image limit
  libweasyl/libweasyl/text.py
Labels: cleanup

#943 Markdown cleanup
  libweasyl/libweasyl/test/test_text.py
  libweasyl/libweasyl/text.py
Labels: cleanup

#944 Speed up Markdown rendering
  libweasyl/libweasyl/defang.py
  libweasyl/libweasyl/test/test_text.py
  libweasyl/libweasyl/text.py
  weasyl/test/web/test_api.py
Labels: bug, cleanup, performance

#945 Cleanup
  libweasyl/libweasyl/alembic/versions/371d1872b404_remove_optimized_image_media_selection.py
  libweasyl/libweasyl/models/tables.py
  weasyl/controllers/api.py
  weasyl/controllers/profile.py
  weasyl/controllers/settings.py
  weasyl/journal.py
  weasyl/media.py
  weasyl/pagination.py
  weasyl/profile.py
  weasyl/submission.py
  weasyl/test/test_pagination.py
  weasyl/test/web/test_api.py
Labels: cleanup

#949 Remove unused `submission.select_*` parameter `exclude`
  weasyl/submission.py
Labels: cleanup

#950 Remove unused and mostly unimplemented content-item settings
  etc/SETTINGS.txt
  libweasyl/libweasyl/models/tables.py
  weasyl/errorcode.py
  weasyl/submission.py
Labels: cleanup

#951 Remove obsolete profile config for tag blocking type
  etc/SETTINGS.txt
  libweasyl/libweasyl/alembic/versions/981bd4df447e_remove_obsolete_tag_blocking_type_.py
  libweasyl/libweasyl/models/tables.py
  weasyl/profile.py
  weasyl/test/test_search.py
Labels: cleanup

#957 Post-Python-3 package changes
  .github/dependabot.yml
  Dockerfile
  etc/requirements.txt
  libweasyl/setup.py
  weasyl/test/test_followuser.py
  weasyl/test/test_search.py
Labels: cleanup

#973 Upgrade Pyramid to 2.0
  etc/requirements.txt
  libweasyl/setup.py
  weasyl/middleware.py
Labels: cleanup, dependencies

#976 Remove measurement of time a request spends queued
  weasyl/middleware.py
  weasyl/polecat.py
Labels: cleanup

#975 Docker fixes
  README-docker.md
  config/site.config.txt.example
  containers/run
  containers/run-nginx
Labels: cleanup

#977 Time request handling parts with monotonic `clock.perf_counter`
  weasyl/cache.py
  weasyl/middleware.py
Labels: cleanup

#979 Pillow 8
  etc/requirements.txt
  libweasyl/setup.py
  weasyl/submission.py
Labels: dependencies, security

#980 Fix visual submission reuploads not regenerating WebP thumbnail
  weasyl/submission.py
Labels: bug

#981 Fix animated GIF processing
  etc/requirements.txt
  weasyl/templates/manage/avatar.html
  weasyl/test/web/test_avatar.py
Labels: bug

#978 Remove forced password resets
  assets/scss/site.scss
  libweasyl/libweasyl/alembic/versions/67e810c14252_remove_forced_password_resets.py
  libweasyl/libweasyl/models/tables.py
  weasyl/controllers/routes.py
  weasyl/controllers/user.py
  weasyl/define.py
  weasyl/login.py
  weasyl/middleware.py
  weasyl/profile.py
  weasyl/resetpassword.py
  weasyl/shout.py
  weasyl/templates/force/resetpassword.html
  weasyl/test/resetpassword/test_force.py
Labels: cleanup

#988 Upgrade pytest to 6.2.2
  requirements/test.txt
  weasyl/test/conftest.py
Labels: dependencies
