Repository Weasyl/weasyl, pull requests merged in 2024-12, with the labels that each got.

#1481 Move profile editor SCSS into its own file
  assets/scss/components/_edit-profile.scss
  assets/scss/site.scss
Labels: cleanup

#1486 fix: Make `searchtag.get_or_create` return id instead of list
  weasyl/searchtag.py
Labels: bug

#1455 Add note on how to run just one module's tests
  README.md
Labels: docs

#1493 Remove duplicate dl.leaders rules in site.scss
  assets/scss/site.scss
Labels: cleanup

#1497 misc
  assets/js/scripts.js
  assets/js/zxcvbn-check.js
  assets/scss/site.scss
  build.js
  package-lock.json
  package.json
  weasyl/controllers/weasyl_collections.py
  weasyl/templates/common/page_start.html
  weasyl/templates/detail/character.html
  weasyl/templates/detail/journal.html
  weasyl/templates/detail/submission.html
  weasyl/templates/modcontrol/suspenduser.html
Labels: cleanup, ui

#1498 Completely disable OAuth
  weasyl/middleware.py
  weasyl/oauth2.py
Labels: security

#1500 Add preload `Link` header only to HTML pages
  weasyl/middleware.py
  weasyl/wsgi.py
Labels: bug, cleanup

#1501 cleanup
  weasyl/controllers/user.py
  weasyl/favorite.py
  weasyl/submission.py
  weasyl/test/web/test_api.py
  wzl
Labels: cleanup

#1503 Add/update `autocomplete`, `inputmode`, and `required` where appropriate
  weasyl/templates/control/2fa/disable.html
  weasyl/templates/control/2fa/generate_recovery_codes.html
  weasyl/templates/control/2fa/init_qrcode.html
  weasyl/templates/control/2fa/init_verify.html
  weasyl/templates/etc/forgotpassword.html
  weasyl/templates/etc/login_box.html
  weasyl/templates/etc/resetpassword.html
  weasyl/templates/etc/signin_2fa_auth.html
Labels: enhancement, ui
