Repository Weasyl/weasyl, pull requests merged in 2025-07, with the labels that each got.

#1522 Fetch search navigation counts asynchronously and approximately
  assets/js/search.js
  weasyl/controllers/general.py
  weasyl/controllers/routes.py
  weasyl/controllers/search.py
  weasyl/search.py
  weasyl/templates/common/page_end.html
  weasyl/templates/etc/search.html
  weasyl/test/test_search.py
Labels: performance

#1571 Require every non-`GET` route to define an explicit CSRF check policy
  weasyl/controllers/api.py
  weasyl/controllers/decorators.py
  weasyl/controllers/routes.py
  weasyl/controllers/user.py
  weasyl/oauth2.py
Labels: cleanup, security

#1579 Speed up single-tag guest searches; improve search page metadata
  weasyl/controllers/general.py
  weasyl/controllers/search.py
  weasyl/search.py
  weasyl/templates/common/page_start.html
  weasyl/test/test_search.py
Labels: enhancement, performance

#1570 Move site update notifications from welcome table to a per-user last-read counter
  assets/scss/components/_text-post-list.scss
  assets/scss/pages/_notifications.scss
  assets/scss/site.scss
  libweasyl/alembic/versions/e63643652458_.py
  libweasyl/models/tables.py
  weasyl/controllers/api.py
  weasyl/controllers/messages.py
  weasyl/controllers/siteupdate.py
  weasyl/define.py
  weasyl/login.py
  weasyl/message.py
  weasyl/siteupdate.py
  weasyl/templates/common/page_start.html
  weasyl/templates/message/notifications.html
  weasyl/templates/siteupdates/list.html
  weasyl/test/conftest.py
  weasyl/test/web/test_site_updates.py
  weasyl/welcome.py
Labels: enhancement

#1580 Prepare to replace combined `profile` char-settings columns and `jsonb_settings` with individual well-typed columns
  libweasyl/alembic/versions/01ae2b302f39_profile_settings_columns.py
  libweasyl/models/tables.py
  libweasyl/models/users.py
  weasyl/controllers/settings.py
  weasyl/controllers/weasyl_collections.py
  weasyl/define.py
  weasyl/login.py
  weasyl/orm.py
  weasyl/profile.py
  weasyl/searchtag.py
  weasyl/templates/admincontrol/manageuser.html
  weasyl/test/db_utils.py
  weasyl/test/test_followuser.py
  weasyl/test/test_marketplace.py
  weasyl/test/test_profile.py
  weasyl/test/test_search.py
  weasyl/test/test_submission.py
  weasyl/test/useralias/test_set.py
  weasyl/test/web/test_api.py
  weasyl/test/web/test_journals.py
  weasyl/test/web/test_notes.py
  weasyl/test/web/test_profile.py
Labels: bug, cleanup

#1573 Tear down database faster in tests
  docker-compose.yml
  libweasyl/alembic/versions/5a073c92aab9_deferrable_foreign_keys_revisited_.py
  libweasyl/conftest.py
  libweasyl/models/tables.py
  libweasyl/test/common.py
  weasyl/test/conftest.py
Labels: cleanup, tests

#1592 Asynchronous view counting
  assets/js/view-count.js
  build.ts
  weasyl/character.py
  weasyl/controllers/content.py
  weasyl/controllers/detail.py
  weasyl/controllers/profile.py
  weasyl/controllers/routes.py
  weasyl/define.py
  weasyl/journal.py
  weasyl/profile.py
  weasyl/submission.py
  weasyl/templates/common/page_start.html
  weasyl/templates/detail/character.html
  weasyl/templates/detail/journal.html
  weasyl/templates/detail/submission.html
  weasyl/templates/user/profile.html
  weasyl/test/test_define.py
  weasyl/test/test_submission.py
  weasyl/test/web/test_api.py
Labels: bug, enhancement, cleanup, performance

#1593 Login form/box improvements
  assets/js/dom.js
  assets/js/login-box.js
  assets/js/scripts.js
  assets/js/util/has-modifier-keys.js
  assets/scss/_reset.scss
  assets/scss/_theme.scss
  assets/scss/components/_login.scss
  assets/scss/site.scss
  build.ts
  weasyl/controllers/two_factor_auth.py
  weasyl/controllers/user.py
  weasyl/define.py
  weasyl/login.py
  weasyl/oauth2.py
  weasyl/templates/common/page_start.html
  weasyl/templates/etc/login_box.html
  weasyl/templates/etc/signin.html
  weasyl/test/login/test_authenticate_bcrypt.py
Labels: enhancement, cleanup, ui
