Repository Weasyl/weasyl, pull requests merged in 2025-01, with the labels that each got.

#1516 Document `./wzl build build-assets` and `PermissionError` fix in readme
  README.md
Labels: docs

#1521 misc
  assets/scss/mod.scss
  assets/scss/site.scss
  weasyl/controllers/moderation.py
  weasyl/forms.py
  weasyl/moderation.py
Labels: bug, cleanup, ui

#1523 fix: Ensure `searchtag._get_or_create` returns results in correct order
  weasyl/searchtag.py
Labels: bug
