Repository Weasyl/weasyl, pull requests merged in 2025-05, with the labels that each got.

#1513 Add embeds for characters and journals
  weasyl/controllers/detail.py
Labels: enhancement

#1541 dev: Prevent internal DNS lookups from leaking to the outside
  Dockerfile
  README.md
  containers/nginx/nginx.conf
  containers/prometheus/Dockerfile
  containers/prometheus/prometheus.yml
  docker-compose.yml
  netferret/.dockerignore
  netferret/.editorconfig
  netferret/.gitignore
  netferret/Cargo.lock
  netferret/Cargo.toml
  netferret/Dockerfile
  netferret/README.md
  netferret/create-container-image.py
  netferret/src/args.rs
  netferret/src/main.rs
  netferret/src/proto.rs
  netferret/src/util.rs
  poetry.lock
  pyproject.toml
Labels: security

#1485 Move detail tag form SCSS into its own file
  assets/scss/components/_detail-tag-form.scss
  assets/scss/site.scss
Labels: cleanup
